name: publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish to crates.io
        if: github.repository == 'durch/rust-s3'
        run: cd s3 && cargo login ${{ secrets.CARGO_TOKEN }} && cargo publish