[package]
name = "webdav_ss"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webdav-handler = "0.2.0"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures-util = { version = "0.3", default-features = false }
anyhow = "1"
percent-encoding = "2.1"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-log = "0.1"
rust-s3 = { git = "https://github.com/durch/rust-s3", rev = "93a7a7fd5d6cac3c2eaaf3ab1606c8536edb8493" }