version: '3'
services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_DOMAIN=localhost
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - miniodata:/data

  nginx:
    image: nginx:1.21
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssc/san_server.crt:/etc/san_server.crt:ro
      - ./ssc/san-private-key.key:/etc/san-private-key.key:ro

volumes:
  miniodata: