name: CI

on:
  push:
    branches: [ staging, trying ]
  pull_request: []

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  nixos-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          system-features = nixos-test benchmark big-parallel kvm
    - run: nix build
    - run: nix flake check

  bors:
    name: ci
    if: ${{ success() }}
    needs:
      - rust-test
      - nixos-tests
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0